import type { CSSProperties } from "react";
import type { ThemeProviderProps } from "@interchain-ui/react";

export const junoTokens = {
  color: {
    canvas: "#05070D",
    canvasElevated: "#080D18",
    panel: "#0B1120",
    panelMuted: "#10172A",
    panelGlass: "rgba(15, 23, 42, 0.78)",
    border: "rgba(139, 92, 246, 0.28)",
    borderStrong: "rgba(124, 58, 237, 0.58)",
    text: "#F7F7FB",
    textMuted: "#AEB8CC",
    textSubtle: "#737F99",
    primary: "#8B5CF6",
    primaryStrong: "#7C3AED",
    primarySoft: "rgba(139, 92, 246, 0.18)",
    indigo: "#4F46E5",
    cyan: "#80EDFF",
    cyanSoft: "rgba(128, 237, 255, 0.12)",
    coral: "#FF9F99",
    coralSoft: "rgba(255, 159, 153, 0.16)",
    success: "#43F0B6",
    warning: "#FBBF24",
  },
  space: {
    xs: "0.5rem",
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
  },
  radius: {
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "1.75rem",
    pill: "999px",
  },
  typography: {
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    headingTracking: "-0.06em",
    eyebrowTracking: "0.14em",
  },
  shadow: {
    panel: "0 24px 70px rgba(0, 0, 0, 0.34)",
    glow: "0 0 42px rgba(139, 92, 246, 0.26)",
  },
} as const;

type ThemeDef = NonNullable<ThemeProviderProps["themeDefs"]>[number];

export const interchainJunoTheme: ThemeDef = {
  name: "juno-dark",
  vars: {
    colors: {
      primary: junoTokens.color.primary,
      background: junoTokens.color.canvas,
      body: junoTokens.color.canvas,
      text: junoTokens.color.text,
      textSecondary: junoTokens.color.textMuted,
      textMuted: junoTokens.color.textSubtle,
      textInverse: junoTokens.color.canvas,
      link: junoTokens.color.cyan,
      linkHover: junoTokens.color.primary,
      cardBg: junoTokens.color.panel,
      inputBg: junoTokens.color.canvasElevated,
      inputBorder: junoTokens.color.border,
      inputBorderFocus: junoTokens.color.primary,
      divider: junoTokens.color.border,
      accent: junoTokens.color.cyan,
      accentText: junoTokens.color.canvas,
      textDanger: junoTokens.color.coral,
      textWarning: junoTokens.color.warning,
      textSuccess: junoTokens.color.success,
      primary50: "#F1EDFF",
      primary100: "#DDD3FF",
      primary200: "#C4B5FD",
      primary300: "#A78BFA",
      primary400: "#8B5CF6",
      primary500: "#7C3AED",
      primary600: "#6D28D9",
      primary700: "#5B21B6",
      primary800: "#4C1D95",
      primary900: "#2E1065",
      purple500: "#8B5CF6",
      purple600: "#7C3AED",
      blue500: "#4F46E5",
      blue600: "#4338CA",
      gray800: "#10172A",
      gray900: "#080D18",
    },
    font: {
      body: junoTokens.typography.fontFamily,
    },
    radii: {
      md: junoTokens.radius.md,
      lg: junoTokens.radius.lg,
      xl: junoTokens.radius.xl,
      full: junoTokens.radius.pill,
    },
  },
};

export const interchainThemeProps = {
  defaultTheme: "dark",
  themeMode: "dark",
  accent: "purple",
  customTheme: interchainJunoTheme.name,
  themeDefs: [interchainJunoTheme],
} satisfies Pick<ThemeProviderProps, "defaultTheme" | "themeMode" | "accent" | "customTheme" | "themeDefs">;

export const junoCssVars = {
  "--juno-color-canvas": junoTokens.color.canvas,
  "--juno-color-canvas-elevated": junoTokens.color.canvasElevated,
  "--juno-color-panel": junoTokens.color.panel,
  "--juno-color-panel-muted": junoTokens.color.panelMuted,
  "--juno-color-panel-glass": junoTokens.color.panelGlass,
  "--juno-color-border": junoTokens.color.border,
  "--juno-color-border-strong": junoTokens.color.borderStrong,
  "--juno-color-text": junoTokens.color.text,
  "--juno-color-text-muted": junoTokens.color.textMuted,
  "--juno-color-text-subtle": junoTokens.color.textSubtle,
  "--juno-color-primary": junoTokens.color.primary,
  "--juno-color-primary-strong": junoTokens.color.primaryStrong,
  "--juno-color-primary-soft": junoTokens.color.primarySoft,
  "--juno-color-indigo": junoTokens.color.indigo,
  "--juno-color-cyan": junoTokens.color.cyan,
  "--juno-color-cyan-soft": junoTokens.color.cyanSoft,
  "--juno-color-coral": junoTokens.color.coral,
  "--juno-color-coral-soft": junoTokens.color.coralSoft,
  "--juno-radius-sm": junoTokens.radius.sm,
  "--juno-radius-md": junoTokens.radius.md,
  "--juno-radius-lg": junoTokens.radius.lg,
  "--juno-radius-xl": junoTokens.radius.xl,
  "--juno-radius-pill": junoTokens.radius.pill,
  "--juno-space-xs": junoTokens.space.xs,
  "--juno-space-sm": junoTokens.space.sm,
  "--juno-space-md": junoTokens.space.md,
  "--juno-space-lg": junoTokens.space.lg,
  "--juno-space-xl": junoTokens.space.xl,
  "--juno-shadow-panel": junoTokens.shadow.panel,
  "--juno-shadow-glow": junoTokens.shadow.glow,
  "--juno-font-body": junoTokens.typography.fontFamily,
  "--juno-heading-tracking": junoTokens.typography.headingTracking,
  "--juno-eyebrow-tracking": junoTokens.typography.eyebrowTracking,
} as CSSProperties;
