import type { CSSProperties } from "react";
import type { ThemeProviderProps } from "@interchain-ui/react";

export const junoTokens = {
  color: {
    canvas: "#0A0203",
    canvasElevated: "#100405",
    panel: "#230A0C",
    panelMuted: "#2E1214",
    panelGlass: "rgba(39, 11, 13, 0.78)",
    border: "rgba(255, 123, 124, 0.12)",
    borderStrong: "rgba(255, 123, 124, 0.35)",
    text: "#FFEBD2",
    textMuted: "#B69C82",
    textSubtle: "#6E5C4A",
    primary: "#FF7B7C",
    primaryStrong: "#E85F60",
    primarySoft: "rgba(255, 123, 124, 0.08)",
    indigo: "#C6484A",
    cyan: "#FF7B7C",
    cyanSoft: "rgba(255, 123, 124, 0.08)",
    coral: "#FF7B7C",
    coralSoft: "rgba(255, 123, 124, 0.12)",
    success: "#8FB08A",
    warning: "#E9A94F",
  },
  space: {
    xs: "0.5rem",
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
  },
  radius: {
    sm: "3px",
    md: "5px",
    lg: "8px",
    xl: "8px",
    pill: "999px",
  },
  typography: {
    fontFamily: "Montserrat, Gotham, 'Helvetica Neue', Arial, sans-serif",
    headingTracking: "0",
    eyebrowTracking: "0.18em",
  },
  shadow: {
    panel: "0 1px 0 rgba(255,235,210,0.03), 0 12px 32px rgba(0,0,0,0.5)",
    glow: "0 0 0 1px rgba(255,123,124,0.4), 0 0 24px rgba(255,123,124,0.28)",
  },
} as const;

type ThemeDef = NonNullable<ThemeProviderProps["themeDefs"]>[number];

export const interchainJunoTheme: ThemeDef = {
  name: "juno-dark",
  vars: {
    colors: {
      primary: junoTokens.color.primary,
      background: junoTokens.color.canvas,
      body: junoTokens.color.canvas,
      text: junoTokens.color.text,
      textSecondary: junoTokens.color.textMuted,
      textMuted: junoTokens.color.textSubtle,
      textInverse: junoTokens.color.canvas,
      link: junoTokens.color.cyan,
      linkHover: junoTokens.color.primary,
      cardBg: junoTokens.color.panel,
      inputBg: junoTokens.color.canvasElevated,
      inputBorder: junoTokens.color.border,
      inputBorderFocus: junoTokens.color.primary,
      divider: junoTokens.color.border,
      accent: junoTokens.color.cyan,
      accentText: junoTokens.color.canvas,
      textDanger: junoTokens.color.coral,
      textWarning: junoTokens.color.warning,
      textSuccess: junoTokens.color.success,
      primary50: "#F1EDFF",
      primary100: "#FFEBD2",
      primary200: "#FFB0B1",
      primary300: "#FF9698",
      primary400: "#FF7B7C",
      primary500: "#E85F60",
      primary600: "#C6484A",
      primary700: "#7A3536",
      primary800: "#351416",
      primary900: "#270B0D",
      purple500: "#FF7B7C",
      purple600: "#E85F60",
      blue500: "#B69C82",
      blue600: "#6E5C4A",
      gray800: "#230A0C",
      gray900: "#100405",
    },
    font: {
      body: junoTokens.typography.fontFamily,
    },
    radii: {
      md: junoTokens.radius.md,
      lg: junoTokens.radius.lg,
      xl: junoTokens.radius.xl,
      full: junoTokens.radius.pill,
    },
  },
};

export const interchainThemeProps = {
  defaultTheme: "dark",
  themeMode: "dark",
  accent: "red",
  customTheme: interchainJunoTheme.name,
  themeDefs: [interchainJunoTheme],
} satisfies Pick<ThemeProviderProps, "defaultTheme" | "themeMode" | "accent" | "customTheme" | "themeDefs">;

export const junoCssVars = {
  "--juno-color-canvas": junoTokens.color.canvas,
  "--juno-color-canvas-elevated": junoTokens.color.canvasElevated,
  "--juno-color-panel": junoTokens.color.panel,
  "--juno-color-panel-muted": junoTokens.color.panelMuted,
  "--juno-color-panel-glass": junoTokens.color.panelGlass,
  "--juno-color-border": junoTokens.color.border,
  "--juno-color-border-strong": junoTokens.color.borderStrong,
  "--juno-color-text": junoTokens.color.text,
  "--juno-color-text-muted": junoTokens.color.textMuted,
  "--juno-color-text-subtle": junoTokens.color.textSubtle,
  "--juno-color-primary": junoTokens.color.primary,
  "--juno-color-primary-strong": junoTokens.color.primaryStrong,
  "--juno-color-primary-soft": junoTokens.color.primarySoft,
  "--juno-color-indigo": junoTokens.color.indigo,
  "--juno-color-cyan": junoTokens.color.cyan,
  "--juno-color-cyan-soft": junoTokens.color.cyanSoft,
  "--juno-color-coral": junoTokens.color.coral,
  "--juno-color-coral-soft": junoTokens.color.coralSoft,
  "--juno-color-success": junoTokens.color.success,
  "--juno-color-warning": junoTokens.color.warning,
  "--coral": junoTokens.color.primary,
  "--coral-bright": "#FF9698",
  "--coral-hot": "#FFB0B1",
  "--coral-deep": junoTokens.color.primaryStrong,
  "--coral-blood": "#C6484A",
  "--coral-a04": "rgba(255, 123, 124, 0.04)",
  "--coral-a08": "rgba(255, 123, 124, 0.08)",
  "--coral-a12": "rgba(255, 123, 124, 0.12)",
  "--coral-a20": "rgba(255, 123, 124, 0.20)",
  "--coral-a35": "rgba(255, 123, 124, 0.35)",
  "--coral-a60": "rgba(255, 123, 124, 0.60)",
  "--maroon": "#270B0D",
  "--maroon-deep": "#1B0708",
  "--void": "#100405",
  "--void-pure": "#0A0203",
  "--cream": junoTokens.color.text,
  "--cream-dim": "#E3CDB2",
  "--cream-mute": junoTokens.color.textMuted,
  "--cream-faint": junoTokens.color.textSubtle,
  "--cream-a06": "rgba(255, 235, 210, 0.06)",
  "--cream-a10": "rgba(255, 235, 210, 0.10)",
  "--cream-a20": "rgba(255, 235, 210, 0.20)",
  "--surface-void": junoTokens.color.canvas,
  "--surface-ground": "#270B0D",
  "--surface-raised": junoTokens.color.panelMuted,
  "--surface-card": junoTokens.color.panel,
  "--surface-inset": junoTokens.color.canvasElevated,
  "--text-primary": junoTokens.color.text,
  "--text-secondary": "#E3CDB2",
  "--text-muted": junoTokens.color.textMuted,
  "--text-faint": junoTokens.color.textSubtle,
  "--text-accent": junoTokens.color.primary,
  "--text-on-coral": "#1B0708",
  "--line-hair": junoTokens.color.border,
  "--line-soft": "rgba(255, 123, 124, 0.20)",
  "--line-strong": junoTokens.color.borderStrong,
  "--line-cream": "rgba(255, 235, 210, 0.10)",
  "--signal-ok": junoTokens.color.success,
  "--signal-warn": junoTokens.color.warning,
  "--signal-live": junoTokens.color.primary,
  "--focus-ring": "rgba(255, 123, 124, 0.60)",
  "--juno-radius-sm": junoTokens.radius.sm,
  "--juno-radius-md": junoTokens.radius.md,
  "--juno-radius-lg": junoTokens.radius.lg,
  "--juno-radius-xl": junoTokens.radius.xl,
  "--juno-radius-pill": junoTokens.radius.pill,
  "--juno-space-xs": junoTokens.space.xs,
  "--juno-space-sm": junoTokens.space.sm,
  "--juno-space-md": junoTokens.space.md,
  "--juno-space-lg": junoTokens.space.lg,
  "--juno-space-xl": junoTokens.space.xl,
  "--juno-shadow-panel": junoTokens.shadow.panel,
  "--juno-shadow-glow": junoTokens.shadow.glow,
  "--juno-font-body": junoTokens.typography.fontFamily,
  "--font-display": junoTokens.typography.fontFamily,
  "--font-body": junoTokens.typography.fontFamily,
  "--font-mono": "'Space Mono', 'IBM Plex Mono', ui-monospace, monospace",
  "--juno-heading-tracking": junoTokens.typography.headingTracking,
  "--juno-eyebrow-tracking": junoTokens.typography.eyebrowTracking,
} as CSSProperties;
